version: '3'
services:

  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: helloworld
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: helloworld

  helloworld:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - 'database'
    environment:
      DB_URL: database
      DB_USERNAME: helloworld
      DB_PASSWORD: helloworld
      DB_PORT: 5432
      DB_NAME: helloworld
      JDBC_DRIVER: postgresql
      # - JDBC_DRIVER="JDBC_DRIVER"
