version: '3'
services:
  helloworld:
    build: .
    ports: 
      - "80:80"
    environment:
      - DB_URL="some_url"
      #- DB_URL="${DB_URL}"
      - DB_USERNAME="${DB_USERNAME}"
      - DB_PASSWORD="${DB_PASSWORD}"
      - DB_PORT="${DB_PORT}"
      - DB_NAME="${DB_NAME}"
      - JDBC_DRIVER="${JDBC_DRIVER}"
